[package]
name = "openmetrics-nom"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"

[dev-dependencies]
rstest = "0.25.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.141"
