[package]
name = "openmetrics-nom"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"

[dev-dependencies]
rstest = "0.23.0"
seq-macro = "0.3.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
